# Generated by Django 4.2.2 on 2024-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=20)),
                ('cardExpireDate', models.CharField(max_length=5)),
                ('cvc', models.CharField(blank=True, max_length=3, null=True)),
                ('verified', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
