# Generated by Django 4.2.2 on 2023-11-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='mark',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
