# Generated by Django 4.2.2 on 2025-01-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_carmodel'),
        ('users', '0002_alter_driver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.color'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.carbrend'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.carmodel'),
        ),
    ]
