# Generated by Django 4.2.2 on 2023-11-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='generated_default_mark',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
