# Generated by Django 4.2.2 on 2023-07-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='UserDocuments/')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='images',
            field=models.ManyToManyField(to='users.documentimages'),
        ),
    ]
