# Generated by Django 4.2.2 on 2023-11-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_generated_default_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='mark',
            field=models.FloatField(blank=True, default=5),
        ),
    ]
