# Generated by Django 4.2.2 on 2023-07-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_documentimages_driver_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'user', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='images',
        ),
        migrations.AddField(
            model_name='client',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='rejected_orders',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='car_color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_images',
            field=models.ManyToManyField(related_name='car_images', to='users.documentimages'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_manufactured_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_tex_passport_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_tex_passport_images',
            field=models.ManyToManyField(related_name='car_text_images', to='users.documentimages'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_images',
            field=models.ManyToManyField(related_name='license_images', to='users.documentimages'),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('busy', 'Busy')], default='active', max_length=20),
            preserve_default=False,
        ),
    ]
