# Generated by Django 4.2.2 on 2023-11-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_driver_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('busy', 'Busy'), ('blocked', 'Block')], default='active', max_length=20),
        ),
    ]
