# Generated by Django 4.2.2 on 2023-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_driver_options_remove_driver_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='airconditioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='immark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='luggage',
            field=models.BooleanField(default=False),
        ),
    ]
