# Generated by Django 4.2.2 on 2023-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_driver_airconditioner_driver_immark_driver_luggage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('busy', 'Busy')], default='active', max_length=20),
        ),
    ]
