# Generated by Django 4.2.2 on 2023-07-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_driver_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='immark',
            new_name='inmark',
        ),
    ]
