# Generated by Django 4.2.2 on 2023-12-01 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_savedlocation'),
        ('users', '0007_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAvailableService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avilable_service', to='users.driver')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.carservice')),
            ],
        ),
    ]
