# Generated by Django 4.2.2 on 2023-09-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_client_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rejected_orders',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
