version: "3.9"
services:

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data_perfectatxi_prod:/data

  perfectaxi:
    build: .
    restart: always
    command: gunicorn PerfectTaxi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/perfectaxi
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  
  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data_perfectaxi_prod:/var/lib/postgresql/data/
    env_file:
      - .env.db

  nginx:
    build: ./nginx
    volumes:
      - .:/home/perfectaxi
    ports:
      - 80:80
    depends_on:
      - perfectaxi

  celery-worker:
    build: .
    container_name: celery-worker
    command: celery -A PerfectTaxi worker -l INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env.prod
    restart: always
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A PerfectTaxi beat -l INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db

  daphne:
    build: .
    container_name: daphne
    command: daphne PerfectTaxi.asgi:application -b 0.0.0.0 -p 8000
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - perfectaxi
      - redis
      - db

volumes:
  postgres_data_perfectaxi_prod:
  redis_data_perfectatxi_prod:
