# base image
FROM python:3.10-alpine

# Working directory
WORKDIR /home/perfectaxi-dev

# set envirement varaiables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt


# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /home/perfectaxi-dev/entrypoint.sh
RUN chmod +x /home/perfectaxi-dev/entrypoint.sh

# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/home/perfectaxi-dev/entrypoint.sh"]