# Generated by Django 4.2.2 on 2024-02-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('fund', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('balance_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('perform_time', models.BigIntegerField(default=0, null=True)),
                ('cancel_time', models.BigIntegerField(default=0, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('preauth', 'Preauth'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('error', 'Error'), ('input', 'Input')], max_length=30, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at_ms', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_operator', models.CharField(blank=True, choices=[('Click', 'Click'), ('PAYME', 'Payme')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charged_fund', models.FloatField()),
                ('charged_time', models.DateTimeField(auto_now_add=True)),
                ('refunded_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=15)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.balance')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
