# Generated by Django 5.1.7 on 2026-04-09 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('payment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driver'),
        ),
        migrations.AddField(
            model_name='charge',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.balance'),
        ),
        migrations.AddField(
            model_name='charge',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
