# Generated by Django 4.2.2 on 2023-10-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('problem', 'Problem'), ('comfort', 'Comfort')], max_length=20, null=True)),
                ('icon', models.ImageField(upload_to='Problems/')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
