# Generated by Django 4.2.2 on 2024-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'Client'), ('driver', 'Driver')], default='client', max_length=20)),
                ('mark', models.PositiveIntegerField()),
                ('time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Reson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('problem', 'Problem'), ('comfort', 'Comfort')], max_length=20, null=True)),
                ('icon', models.FileField(upload_to='Problems/')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
