# Generated by Django 4.2.2 on 2023-11-13 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver_mark'),
        ('feedback', '0003_feedback_time_alter_reson_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
