# Generated by Django 4.2.2 on 2025-02-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_client_remove_feedback_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='resons',
            field=models.ManyToManyField(blank=True, to='feedback.reson'),
        ),
    ]
