# Generated by Django 4.2.2 on 2024-01-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_options_alter_feedback_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('client', 'Client'), ('driver', 'Driver')], default='client', max_length=20),
        ),
    ]
