# Generated by Django 4.2.2 on 2024-01-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('admin', 'Admin')], default='public', max_length=10),
        ),
    ]
