# Generated by Django 5.1.7 on 2025-03-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminchatroom',
            options={'ordering': ['closed']},
        ),
    ]
