# Generated by Django 4.2.2 on 2023-10-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('standart', 'Standart'), ('bussiness', 'Bussiness'), ('comfort', 'Comfort')], max_length=100, null=True)),
                ('includedCars', models.CharField(max_length=255, null=True)),
                ('start_price', models.IntegerField(default=0)),
                ('price_per_km', models.FloatField(default=0)),
            ],
        ),
    ]
