# Generated by Django 4.2.2 on 2023-08-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='start_price',
            field=models.IntegerField(default=0),
        ),
    ]
