# Generated by Django 4.2.2 on 2024-01-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_savedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='free_wait_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carservice',
            name='price_per_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='carservice',
            name='wait_price_per_min',
            field=models.FloatField(default=0),
        ),
    ]
