# Generated by Django 4.2.2 on 2023-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_carservice_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='price_per_km',
            field=models.FloatField(default=0),
        ),
    ]
