# Generated by Django 4.2.2 on 2025-02-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_carmodel_brend'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='CategoryIcons/'),
        ),
    ]
