# Generated by Django 4.2.2 on 2024-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRadius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius1', models.IntegerField(default=1000)),
                ('radius2', models.IntegerField(default=2000)),
                ('radius3', models.IntegerField(default=3000)),
                ('radius4', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
