# Generated by Django 4.2.2 on 2023-11-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRadius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius1', models.IntegerField(default=1000)),
                ('radius2', models.IntegerField(default=2000)),
                ('radius3', models.IntegerField(default=3000)),
                ('radius4', models.IntegerField(default=5000)),
            ],
        ),
    ]
