# Generated by Django 4.2.2 on 2023-10-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=35, null=True)),
                ('start_adress', models.CharField(blank=True, max_length=255, null=True)),
                ('start_point', models.CharField(blank=True, max_length=40, null=True)),
                ('ordered_time', models.DateTimeField(auto_now_add=True)),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
                ('complated_time', models.DateTimeField(blank=True, null=True)),
                ('rejected_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='active', max_length=15)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('carservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.carservice')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('cost', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=40, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
