# Generated by Django 4.2.2 on 2023-08-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='active', max_length=15),
        ),
    ]
