# Generated by Django 4.2.2 on 2023-10-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arived_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='started_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
