# Generated by Django 4.2.2 on 2024-10-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
