# Generated by Django 4.2.2 on 2023-12-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_arived_time_order_started_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='active', max_length=15),
        ),
    ]
