# Generated by Django 4.2.2 on 2024-11-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='order.order'),
        ),
    ]
