# Generated by Django 4.2.2 on 2023-08-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_carservice_price_per_km'),
        ('order', '0003_alter_order_client_alter_order_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.carservice'),
        ),
    ]
