# Generated by Django 4.2.2 on 2023-08-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_carservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, to='order.services'),
        ),
    ]
