# Generated by Django 4.2.2 on 2023-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_options_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
