# Generated by Django 4.2.2 on 2024-01-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_driveravailableservice'),
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='point_number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='DriverOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('delivering', 'Delivering'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
